In [1]:
from google.colab import files
uploaded = files.upload()

Saving Base Novelas.xlsx to Base Novelas.xlsx

In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_excel('Base Novelas.xlsx')
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,Rótulos de Linha,Média de Audiência2,NaN,Rótulos de Linha,Média de Audiência2
2,1972,27.97,NaN,Ivani Ribeiro,44.1175
3,1973,27.06,NaN,Gonzaga Blota,40.02
4,1975,37.163333,NaN,Herval Rossano,48.74

In [8]:
df.shape
df.columns
df.dtypes
df.isnull().sum()
df.nunique()
df.describe()

       Unnamed: 2
count         0.0
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

In [9]:
df = df.drop_duplicates()

In [10]:
df = df.dropna()

In [12]:
df.head()
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [13]:
df = pd.read_excel('Base Novelas.xlsx', header=1)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Base Novelas.xlsx'

In [14]:
df = pd.read_excel('Base Novelas.xlsx', header=1)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Base_Novelas.xlsx'

In [16]:
df = pd.read_excel('/content/Projeto_Final-_Ada/Base_Novelas.xlsx', header=1)
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Rótulos de Linha,Média de Audiência2,NaN,Rótulos de Linha,Média de Audiência2
1,1972,27.97,NaN,Ivani Ribeiro,44.1175
2,1973,27.06,NaN,Gonzaga Blota,40.02
3,1975,37.163333,NaN,Herval Rossano,48.74
4,1976,39.43,NaN,Roberto Talma,38.53

In [17]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Rótulos de Linha,Média de Audiência2,NaN,Rótulos de Linha,Média de Audiência2
1,1972,27.97,NaN,Ivani Ribeiro,44.1175
2,1973,27.06,NaN,Gonzaga Blota,40.02
3,1975,37.163333,NaN,Herval Rossano,48.74
4,1976,39.43,NaN,Roberto Talma,38.53

In [19]:
df = pd.read_excel('/content/Projeto_Final-_Ada/Base_Novelas.xlsx', skiprows=1, header=0)

# pegar só as 2 primeiras colunas (que agora são 'Rótulos de Linha' e 'Média de Audiência2')
df1 = df[['Rótulos de Linha', 'Média de Audiência2']]

# renomear colunas
df1.columns = ['Ano', 'Audiencia']

df1.head()

                Ano            Audiencia
1  Rótulos de Linha  Média de Audiência2
2              1972                27.97
3              1973                27.06
4              1975            37.163333
5              1976                39.43

In [20]:
df1.dtypes

Ano          object
Audiencia    object
dtype: object

In [21]:
df1['Ano'] = pd.to_numeric(df1['Ano'], errors='coerce')
df1['Audiencia'] = pd.to_numeric(df1['Audiencia'], errors='coerce')

In [22]:
df1.dtypes

Ano          float64
Audiencia    float64
dtype: object

In [23]:
df1 = df1.dropna()

In [24]:
df1.isnull().sum()

Ano          0
Audiencia    0
dtype: int64